---
linters-settings:
  gocyclo:
    min-complexity: 15

  staticcheck:
    go: "1.21"
    # https://staticcheck.io/docs/options#checks
    checks: ["all", "-SA1019"]

  gocognit:
    min-complexity: 20

  forbidigo:
    forbid:
      - domain.Validator
      # - (http|HTTP)
      # - documentModel
      - p: http.StatusAccepted
        msg: A
        

    analyze-types: true



# - documentModel
# - fmt\.Print.*