---
app:
  name: golang-structure
  httpPort: 8080
  metricsPort: 8081
db:
#   driverName: sqlite3
#   sqlite3:
#     file: app.db
  driverName: mysql
  mysql:
    username: user
    password: password
    host: 127.0.0.1
    port: 3306
    database: development
# auth:
#   signingKey: ah5T9Y9V2JPU74fhCtHQfDqLp3Zg8ZNc
#   accessTokenTtlMin: 5
#   refreshTokenTtlHour: 720
#   googleCallbackUrl: http://localhost:5173/app/callback
#   googleClientId: 830416463276-3ts1rsinahi0hdnsfc10m6mabpttrd5i.apps.googleusercontent.com
#   googleClientSecret: $GOOGLE_CLIENT_SECRET
#   apiTimeoutSec: 5
trace:
  exporter: jaeger
  jaeger:
    endpoint: http://localhost:14268/api/traces
cors:
  allowOrigins:
    - "*"
shutdown:
  timeSec1: 1
  timeSec2: 1
log:
  level:
    default: debug
    golang-structure: debug
swagger:
  enabled: true
  host: localhost:8080
  schema: http
debug:
  ginMode: true
  # wait: true
